apiVersion: v1
kind: Template
metadata:
  name: ace-s2i-demo
  annotations:
    tags: java, web app
    template.openshift.io/provider-display-name: "IBM"
    description: ACE application builder demo
labels:
  application: ace-s2i-demo
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: "https://github.com/tdolby-at-uk-ibm-com/ace-s2i-demo"
    required: true
  - name: APP_NAME
    description: The name of the application that you would like to build.
    displayName: App name
    value: "ace-s2i-demo"
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled binaries from your open liberty builder
    displayName: Output Directory
    value: /tmp/ace-server
    required: false
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ace-s2i-demo-builder
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ace-s2i-demo-runtime
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ace-s2i-builder-image
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: tdolby.dolbyfamily.org:52367/ace-s2i-builder-image
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ace-s2i-runtime-image
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: tdolby.dolbyfamily.org:52367/ace-s2i-runtime-image
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ace-s2i-demo
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ace-s2i-demo:0.1.0
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
        from:
          kind: ImageStreamTag
          name: ace-s2i-builder-image:0.1.0
        incremental: false
      type: Source
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ace-s2i-demo
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ace-s2i-demo:0.1.0
    postCommit: {}
    resources: {}
    source:
      type: Image
      images:
        - from:
            kind: ImageStreamTag
            name: ace-s2i-builder-image:0.1.0
          paths:
            - destinationDir: .
              sourcePath: /tmp/src/
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ace-s2i-runtime-image:0.1.0
        incremental: false
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: ${APP_NAME}
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - image: ace-s2i-demo:0.1.0
          imagePullPolicy: IfNotPresent
          name: ace-s2i-demo
          ports:
          - containerPort: 7800
            name: http
            protocol: TCP
          metadata:
            labels:
              app: ${APP_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: http
      port: 7800
    selector:
      app: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 7800
    to:
      kind: Service
      name: ${APP_NAME}
